### PR TITLE
Feature/support japanese language

### PR DESCRIPTION
**Pull request by pierrephi**
Here comes Japanese
I took the opportunity to factorise the algorithm for the display hour and minutes rounding, I thought I was clever until I applied it to Dutch :)
All languages updated and tested, I would test Dutch if I were you before merging just in case!

While testing the NL version I fixed a bug (crash when midnight), there was no word for 0 (I used TWAALF)

### CODE REVIEW

**Comment by pierrephi** [comment]
Do tell me if I need to implement things in a different way, I am far from an advanced JS/node developper, just learning :)

**Comment by ngnijland** [comment]
Thanks! I know the code could be improved, but never took the time to do so 👍 Sorry for the late response, I had a very busy week.

To test the code I'll use this on my smart mirror for the coming week switching between some languages and I'll merge it next weekend!

**Comment by pierrephi** [comment]
No worries I also have the code ready to alternate between a list of languages every x minutes but it comes on top of this pull request I can push it if you want as well. That’s pretty cool for testing :)

**Comment by ngnijland** [comment]
Please do so!

**Review by ngnijland — APPROVED** [review]

**Pull request merged**
