### PR TITLE
Feature/support spanish language

### PR DESCRIPTION
**Pull request by pierrephi**
Sorry for the noise I have been struggling a bit with my merges..
Here is Spanish, after the French port. I might do Japanese next :)

### CODE REVIEW

**Review by ngnijland — APPROVED** [review]

**Comment by ngnijland** [comment]
Wow, you know your languages! I would be very interested to see a Japanese version. Thanks for this one!

**Comment by pierrephi** [comment]
Working on it :)

Then I intend to add an option so that you provide a list of languages that alternate  at a predefined interval 

Pierre-Phi
--
Computers are like air conditioners they stop working correctly when you open windows.

**Comment by ngnijland** [comment]
Love it! Do you have any pictures somewhere of your smart mirror? Would love to see!

**Comment by pierrephi** [comment]
I haven’t assembled it yet just working on the software part for now, promise I will share it when it is done :)

Pierre-Phi
--
Computers are like air conditioners they stop working correctly when you open windows.

**Comment by pierrephi** [comment]
you approved but it didn't merge into master yet, missing something?

**Comment by ngnijland** [comment]
Nope, just forgot to hit the merge button 😅 Thanks for the heads up!

**Pull request merged**
