### PR TITLE
feat: add language alternation

### PR DESCRIPTION
**Pull request by ngnijland**

### CODE REVIEW

**Comment by ngnijland** [comment]
@pierrephi it didn't come out as neat as I thought I would be able to make it. Still, what do you think? (I couldn't push to your forked repo, that's why I created a new pull request here)

**Comment by ngnijland** [comment]
This PR will possibly replace #9

**Comment by pierrephi** [comment]
Yes that looks fine and elegant, I now see the mistake I made in setInterval..
I will find a way to merge this back into my work :)

**Comment by pierrephi** [comment]
Do you mind merging this branch into master so that I realign my fork with the latest (before I do Anything else)

**Pull request merged**
