### PR TITLE
Feature/language alternation

### PR DESCRIPTION
**Pull request by pierrephi**
Here is the branch with the automatic language alternation
just add something like:

```
    languageAlternationList: ['nl', 'fr', 'en', 'jp', 'es'],
    languageAlternationInterval: 10
```
to the config, language will change every 10 mins
This includes the other pull request for Japanese language

### CODE REVIEW

**Comment by ngnijland** [comment]
I'm running it on my mirror!

**Comment by pierrephi** [comment]
So how do you find this ?

**Comment by pierrephi** [comment]
it seems you merge master in the branch language alternation and not the opposite ?

```
Niek ngnijland@gmail.com

Merge branch 'master' into feature/language-alternation

```

**Comment by ngnijland** [comment]
Yes, I merged the Japanese language in and then updated this branch to master so I could have a look at the language alternation code in isolation! To be honest the code on this one can be improved a bit. I think the validating and the setting up of the alternation variables is a little verbose. Also, I found that the update `setInterval` function is called several times resulting in multiple intervals running in parallel. See the following screenshot:

Screenshot 2021-02-09 at 20 04 21

I set the language alternation interval to 6 seconds. Normally the clock will update every 10 seconds, but now as you can see the more the language alternates the more times the clock is updated in the 6 seconds between an alternation 😁 

I'll give the feature a shot and create a pull request to this branch if you're okay with that? :)

**Comment by pierrephi** [comment]
Yes sure as I said I am far from proficient in JS/node so happy to learn...

Sneak peak at my next language ...
image

Much more complicated as you cannot breakdown Arabic in letters but only words ... plus right to left ...

**Comment by ngnijland** [comment]
How do you know al these languages?:o Awesome!

**Comment by pierrephi** [comment]
I am learning Arabic on Duolingo this project is good practice :)

Still have Italian to go and then I will leave it to someone else to add new languages :)

**Comment by ngnijland** [comment]
Awesome! Looking forward to that one as well!

**Pull request closed without merging**
