### PR TITLE
Feature/support italian language

### PR DESCRIPTION
**Pull request by pierrephi**
Here comes Italian !
My last language :)

### CODE REVIEW

**Review by ngnijland — APPROVED** [review]

**Comment by ngnijland** [comment]
Really nice! I appreciate the effort you put into this module! Have fun with it!:)

Please do share some pictures of your mirror when it's done!

**Comment by pierrephi** [comment]
I will!

**Comment by pierrephi** [comment]
Next clock project ? https://vimeo.com/106152643 :)

**Comment by ngnijland** [comment]
Haha, that's interesting. I leave that module up to you though 😜

**Comment by pierrephi** [comment]
I need to work on the hardware side now :) I will leave this to later :)

**Comment by pierrephi** [comment]
As promised :)

https://www.instagram.com/p/CQEKwI6jgh_/?utm_medium=copy_link

Pierre-Phi
--
Computers are like air conditioners they stop working correctly when you open windows.

**Comment by ngnijland** [comment]
Very cool! How did you do the Google assistant part?😁

**Comment by pierrephi** [comment]
Cf MMM-GoogleAssistant :)

Pierre-Phi!
http://www.pierrephi.net
http://www.flickr.com/photos/pierrephi
--
Computers are like air conditioners, they stop working properly when you open windows!

**Comment by ngnijland** [comment]
Thanks!

**Pull request merged**
